name: Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '22'
        cache: 'npm'
        cache-dependency-path: 'frontend/server/package-lock.json'
    - run: cd frontend/server && npm install
    - run: cd frontend/server && npm run lint
    - run: cd frontend/server && npm run type-check
    - run: cd frontend/server && npm run test

  backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
    - run: pip install -r requirements.txt
    - run: pytest tests/
